# Ejemplo 2. DFT e IDTF para Calcular la Respuesta de un Filtro FIR.

In [1]:
import numpy as np
from numpy import pi

In [2]:
h = [1, 2, 3]
M = len(h)
x = [1, 2, 2, 1]
L = len(x)

In [3]:
def N_adecuado(M, L):
    N = M + L - 1
    for i in range(1000):
        if 2**i >= N:
            N = 2**i
            return N
    return 0

In [4]:
N = N_adecuado(M, L)
print('El N adecuado es:', N)

El N adecuado es: 8


In [5]:
def DFT(x, N):
    X = []
    for k in range(N):
        sum = 0
        for n in range(len(x)):
            sum += x[n]*np.exp(-1j*2*pi*k*n/N)
        X.append(sum)
    return np.array(X, 'complex_')

In [6]:
X = DFT(x, N)
X

array([ 6.        +0.00000000e+00j,  1.70710678-4.12132034e+00j,
       -1.        -1.00000000e+00j,  0.29289322-1.21320344e-01j,
        0.        -1.22464680e-16j,  0.29289322+1.21320344e-01j,
       -1.        +1.00000000e+00j,  1.70710678+4.12132034e+00j])

In [7]:
H = DFT(h, N)
H

array([ 6.        +0.00000000e+00j,  2.41421356-4.41421356e+00j,
       -2.        -2.00000000e+00j, -0.41421356+1.58578644e+00j,
        2.        +4.89858720e-16j, -0.41421356-1.58578644e+00j,
       -2.        +2.00000000e+00j,  2.41421356+4.41421356e+00j])

In [8]:
Y = X*H
Y

array([ 3.60000000e+01+0.00000000e+00j, -1.40710678e+01-1.74852814e+01j,
       -1.55431223e-15+4.00000000e+00j,  7.10678119e-02+5.14718626e-01j,
        5.99903913e-32-2.44929360e-16j,  7.10678119e-02-5.14718626e-01j,
        2.44249065e-15-4.00000000e+00j, -1.40710678e+01+1.74852814e+01j])

In [9]:
def IDFT(X, N):
    x = []
    for n in range(N):
        sum = 0
        for k in range(len(X)):
            sum += X[k]*np.exp(1j*2*pi*k*n/N)
        x.append(sum/N)
    return np.array(x, 'complex_')

In [10]:
y = IDFT(Y, N)
y

array([1.00000000e+00-8.88178420e-16j, 4.00000000e+00+0.00000000e+00j,
       9.00000000e+00-6.66133815e-16j, 1.10000000e+01+2.16493490e-15j,
       8.00000000e+00+4.44089210e-16j, 3.00000000e+00+2.22044605e-15j,
       3.10862447e-15-1.77635684e-15j, 8.88178420e-16+1.12687637e-14j])